### ISSUE TITLE
 $output not set if table prefix is wrong (missing '_')

### ISSUE THREAD

**Issue by matthias-meisinger** [tessus/mwExtensionMantis#13]
Expected Behaviour: There should be a Warning/Error.
Instead: log file just shows that $output is not set.

Cause: If statement on line 443 is missing the else clause.

Environment:
MediaWiki	1.26.2
PHP	5.6.29-0+deb8u1 (apache2handler)
MySQL	5.5.54-0+deb8u1
MantisBT-Version	1.3.0
Schema-Version	209

**Comment by tessus** [comment]
Pull request #18 contains the fix for this. I will apply the pull request, although I have to tweak the code a bit.
