### ISSUE TITLE
Using a single bugid is not showing anything

### ISSUE THREAD

**Issue by matthias-meisinger** [tessus/mwExtensionMantis#15]
Expected Behaviour: The set Issue shows up on the wiki page. 
Instead: Nothing shows (No error/warning).

Cause: Array call $conf[bugid] is missing apostrophs in some places.
Fix: $conf[bugid] -> $conf['bugid']

Environment:
MediaWiki	1.26.2
PHP	5.6.29-0+deb8u1 (apache2handler)
MySQL	5.5.54-0+deb8u1
MantisBT-Version	1.3.0
Schema-Version	209

**Comment by tessus** [comment]
I am not able to reproduce the issue. Do you get any warnings/error in the php error log (the one that is specified in `/etc/php.ini`)?

Product | Version
-------- |---------
MediaWiki |  1.26.3
PHP | 5.6.30 (apache2handler)
MySQL | 5.6.25
MantisBT Version | 1.2.19
Schema Version | 183

**Comment by matthias-meisinger** [comment]
Can't. I already fixed it on my system.

Am 21.02.2017 17:59 schrieb "Helmut K. C. Tessarek" <
notifications@github.com>:

**Comment by tessus** [comment]
No idea why this is not working for you. However, single quotes for keys is better PHP coding.
Will apply #16
