### ISSUE TITLE
Missing UTF8 support

### ISSUE THREAD

**Issue by matthias-meisinger** [tessus/mwExtensionMantis#17]
Expected Behaviour: German umlauts should be displayed correctly
Instead: Messed up gibberish.

Cause: Strings are not utf8 encoded.

Environment:
MediaWiki	1.26.2
PHP	5.6.29-0+deb8u1 (apache2handler)
MySQL	5.5.54-0+deb8u1
MantisBT-Version	1.3.0
Schema-Version	209

**Comment by tessus** [comment]
Fixed by #18.
