### ISSUE TITLE
more flexible filtering for version, target_version, fixed_in_target

### ISSUE THREAD

**Issue by tessus** [tessus/mwExtensionMantis#24]
/ref https://github.com/tessus/mwExtensionMantis/pull/20#issuecomment-327613654
/cc @pedwik

**Comment by pedwik** [comment]
There seems to be some interference when including both "status" and "fixed_in" parameters:
When defining 
status = closed
fixed_in = 2.7.0 
I get matches. But when defining 
status = closed, resolved 
fixed_in = 2.7.0
I get the error message 
No MANTIS entries with status 'open' and fixed_in_version '2.7.0' found.

**Comment by tessus** [comment]
`status` does not take more than 1 value. since it couldn't interpret the result, it fell back to the default, which is `open`. please use `all` for now. I opened #6 a few years back, but I was always busy with other stuff and thus forgot about it.

I'm off to bed. I gotta get up in 4 hours...

**Comment by tessus** [comment]
Range filtering will be possible, by specifying the following operators in the following list:

`gt`, `ge`, `lt`, `le`

Example:

```
<mantis>
status = resolved, closed
fixed_in_version = gt 2.71
</mantis>
```

It will also be possible to use a range:

```
<mantis>
status = resolved, closed
fixed_in_version = gt 2.71, le 3.0
</mantis>
```
