### ISSUE TITLE
Question: Support for Sql Server

### ISSUE THREAD

**Issue by pedwik** [tessus/mwExtensionMantis#28]
We have moved our MantisBT to a Windows server, and replaced the database with Sql Server. Will the extension work with Sql Server, and with the database on a remote server?

**Comment by tessus** [comment]
> We have moved our MantisBT to a Windows server, and replaced the database with Sql Server. 

My condolences.

>Will the extension work with Sql Server, and with the database on a remote server?

No. The extension is written for mysql. All the database related calls are for mysqli.

**Comment by pedwik** [comment]
I suggest adding that limitation to the documentation (https://www.mediawiki.org/wiki/Extension:Mantis). MantisBT supports Sql Server and so does the MediaWiki-engine nowadays.

**Comment by tessus** [comment]
Good idea. Will do. SQL Server wasn't supported in Mantis when I started this project, I also created this extension as a successor of another extension, which had the MySQL part in the documentation.

**Comment by pedwik** [comment]
But I have migrated the database back to MySql, so the extension should work.

**Comment by tessus** [comment]
Wrong ticket. :-) It does work. The PHP version you seem to be using is out of support for the last 2 years.

**Comment by tessus** [comment]
Btw, if you want SQL Server support, I'm sure you can add this rather quickly. I used ANSI SQL, thus you shouldn't have any issues with the queries (unless MS doesn't follow the standard).
The only problem is that you have to make it run (error free) for people who do not have the extension loaded. You will get PHP compile errors when referencing functions which are not available.

I'm more than happy to accept a pull request.

I'm keeping this open until I'll have added a note to the documentation.

**Comment by tessus** [comment]
documentation updated
