### ISSUE TITLE
Mediawiki crashes is using version 2.0

### ISSUE THREAD

**Issue by pedwik** [tessus/mwExtensionMantis#29]
When using version 2.0, my MediaWiki crashes. If reverting back to 1.6 it works.

**Comment by tessus** [comment]
I'm sorry, but this does not help a bit.

How doses it crash?
What version of mediawiki? 
What's in the crash log? 
What is in the PHP error log?

**Comment by pedwik** [comment]
MediaWiki version is 1.20.3. 
The error message displayed in the browser is 
"This page isn’t working
xxxx.org is currently unable to handle this request.
HTTP ERROR 500"
The only thing I do to make it work again is to replace Mantis.php version 2.0 with version 1.6. From the mediwiki's error log:

[15-Sep-2017 10:59:37 Europe/Stockholm] PHP Parse error:  syntax error, unexpected '[' in .../public_html/mw/extensions/Mantis/Mantis.php on line 61
[15-Sep-2017 12:25:01 Europe/Stockholm] PHP Warning:  preg_match() [<a href='function.preg-match'>function.preg-match</a>]: Empty regular expression in .../public_html/mw/extensions/WikiArticleFeeds/WikiArticleFeeds_body.php on line 430

Please tell me if you need more info, the mediawiki is on a shared hosting server but I can probably find out how to error logs from php too.

**Comment by tessus** [comment]
Hmm, the parse error is weird. I don't get it. I have to look into it. Maybe I forgot an edge case you triggered.

**Comment by tessus** [comment]
ah, wait. what PHP version are you using? < 5.4?

**Comment by tessus** [comment]
I changed array initializations to the new form, since I've noticed a weird side effect with the old one.

`$a = array();` does not clear the array. If there are elements in the array, they will persist. Thus I changed them to `$a = [];` which is apparently not supported on PHP < 5.4.

**Comment by tessus** [comment]
I will create a separate branch tonight where I'll revert my changes related to arrays.
Then it _should_ work on PHP <5.4.

Please note that I can't really support setups which are out of support for years.

**Comment by pedwik** [comment]
I understand, maybe a good idea to add that as a requirement on the homepage too? The wiki is hosted where PHP is 5.6 as default, but the wiki installation obviously has its own PHP package. We got problems a couple of years ago with some extensions that stopped working and therefore sticked to 1.20.3.

**Comment by tessus** [comment]
Ok, I'll add that to the documentation too. I really did not think that I'd have to.

Even PHP 5.6 is out of support, let alone 5.3.

Ok, please try https://github.com/tessus/mwExtensionMantis/tree/ancient-php

Checkout branch `ancient-php`.

**Comment by tessus** [comment]
I won't be available for the next 4 hours. If you have any issues, please let me know.
I'll look at them tonight or tomorrow.

**Comment by pedwik** [comment]
After updating to version 5.6 it works. It was very confusing in cpanel (we have the wiki on a shared hosting), it indicated that php 5.6 was used, but you had to select it and set it too....

**Comment by tessus** [comment]
Great. I believe upgrading PHP ws long overdue. ;-)

Please note that PHP 5.6 is also out of support, but I don't think you will run in any issues with 5.6. At least not with my extension.

Closing this now.
