### ISSUE TITLE
Notice when using comma to separate orderby columns

### ISSUE THREAD

**Issue by pedwik** [tessus/mwExtensionMantis#33]
The following example raises a warning when using the orderby argument with two columns separeate by a comma. Message is "Notice: Undefined offset   ...Mantis.php on line 329"
<mantis>
status = resolved, closed
fixed_in_version = 2.8.1, 2.9.0
show = id,category, summary, fixed_in_version, updated, resolution
orderby = category, summary
</mantis>

**Comment by tessus** [comment]
Will have a look at it later today.

**Comment by tessus** [comment]
What is the entire error message? (The ... part.)

**Comment by tessus** [comment]
Never mind.
This also is only a notice and does not change the behaviour of the code.

The code still works.

**Comment by tessus** [comment]
fixed in https://github.com/tessus/mwExtensionMantis/commit/e27a428b74dcbf58f84b7cea97329b80599243a3

**Comment by pedwik** [comment]
The ... part is the file path to mantis.php

Mvh Peder
