### ISSUE TITLE
wishlist: apply mediawiki formating rules

### ISSUE THREAD

**Issue by ka7** [tessus/mwExtensionMantis#36]
( checked with code https://github.com/wikimedia/mediawiki-tools-codesniffer )

result can be viewed here.
https://github.com/tessus/mwExtensionMantis/compare/master...ka7:phpcs_autofixed?expand=1

**Comment by tessus** [comment]
Sorry, I use my own coding conventions.

I truly dislilke K&R style braces and that's never going to happen in my code. I checked the link and most of the code is less readable than before.
